version: '2.3'

services:
  lorascral:
    build:
      context: .
    image: monicaproject/lorascral:latest
    command: ["dotnet","./Lora-Scral.dll"]
    volumes:
      - "./config:/etc/lorascral"