version: '2.3'

services:
  lorascral:
    build:
      context: .
    image: monicaproject/lora-scral-project:latest
    command: ["mono","./Lora-Scral.exe"]
    volumes:
      - "./config/settings.conf:/etc/monicascral/settings.conf"

